apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-node
  namespace: tasks-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks-node
  template:
    metadata:
      labels:
        app: tasks-node
    spec:
      containers:
      - name: tasks-node
        image: tasks-node:1.0  # Será atualizado
        imagePullPolicy: Never
        ports:
        - containerPort: 2750
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"