apiVersion: v1
kind: Service
metadata:
  name: tasks-node
  namespace: tasks-node
spec:
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 31500
  selector:
    app: tasks-node