apiVersion: v1
kind: Service
metadata:
  name: tasks-node
  namespace: tasks-node
spec:
  type: ClusterIP
  clusterIP: 10.96.18.4
  ports:
    - port: 2750
      targetPort: 2750
  selector:
    app: tasks-node