apiVersion: v1
kind: Service
metadata:
  name: tasks-db
spec:
  type: NodePort
  selector:
    app: tasks-db
  ports:
    - protocol: TCP
      port: 3307          # Porta interna do serviço no cluster
      targetPort: 3307    # Porta no contêiner (o MariaDB estará ouvindo na 3307)
      nodePort: 32051     # Porta no nó (exposta externamente)
