apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-node
  namespace: users-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-node
  template:
    metadata:
      labels:
        app: users-node
    spec:
      containers:
      - name: users-node
        image: node-app:1.0  # Será atualizado
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"