apiVersion: v1
kind: Service
metadata:
  name: users-node
  namespace: users-node
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32000
  selector:
    app: users-node