apiVersion: v1
kind: Service
metadata:
  name: users-node
  namespace: users-node
spec:
  type: ClusterIP
  clusterIP: 10.96.18.5
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: users-node