apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-node
  namespace: auth-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-node
  template:
    metadata:
      labels:
        app: auth-node
    spec:
      containers:
      - name: auth-node
        image: auth-node:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 2500
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"