apiVersion: v1
kind: Service
metadata:
  name: auth-node
  namespace: auth-node
spec:
  type: ClusterIP
  clusterIP: 10.96.18.3
  ports:
    - port: 2500
      targetPort: 2500
  selector:
    app: auth-node