apiVersion: apps/v1
kind: Deployment
metadata:
  name: maria-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maria-db
  template:
    metadata:
      labels:
        app: maria-db
    spec:
      containers:
      - name: maria-db
        image: mariadb:10.11
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Kubernetes@"
        - name: MYSQL_TCP_PORT
          value: "3306"
        volumeMounts:
        - name: maria-db-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: maria-db-persistent-storage
        persistentVolumeClaim:
          claimName: maria-db-pvc
