apiVersion: v1
kind: Service
metadata:
  name: maria-db
spec:
  type: NodePort
  clusterIP: 10.96.18.10
  selector:
    app: maria-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30000
