apiVersion: v1
kind: Service
metadata:
  name: maria-db
spec:
  type: NodePort
  selector:
    app: maria-db
  ports:
    - protocol: TCP
      port: 3306          # Porta interna do serviço no cluster
      targetPort: 3306    # Porta no contêiner (o MariaDB estará ouvindo na 3307)
      nodePort: 30000     # Porta no nó (exposta externamente)
