apiVersion: v1
kind: Service
metadata:
  name: users-db
spec:
  type: NodePort
  selector:
    app: users-db
  ports:
    - protocol: TCP
      port: 3308          # Porta interna do serviço no cluster
      targetPort: 3308    # Porta no contêiner (o MariaDB estará ouvindo na 3307)
      nodePort: 32052     # Porta no nó (exposta externamente)
